server:
  port: 8081
spring:
  security:
    user:
      name: testadmin
      password: password
      manager:
  kafka:
    consumer:
      bootstrap-servers: 10.1.1.5:9093
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      ssl.trust-store-location: /home/vcap/app/certs/client.truststore
      ssl.trust-store-password: 123456
      ssl.key-store-location: /home/vcap/app/certs/ssldemo.keystore
      ssl.key-store-password: 123456
      ssl.key-password: 123456
      ssl.protocol: TLSv1.2
      ssl.trust-store-type: PKCS12
      ssl.key-store-type: PKCS12
    producer:
      bootstrap-servers: 10.1.1.5:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl.trust-store-location: /home/vcap/app/certs/client.truststore
      ssl.trust-store-password: 123456
      ssl.key-store-location: /home/vcap/app/certs/ssldemo.keystore
      ssl.key-store-password: 123456
      ssl.key-password: 123456
      ssl.protocol: TLSv1.2
      ssl.trust-store-type: PKCS12
      ssl.key-store-type: PKCS12