server:
  port: 8081
logging:
  level:
    root: INFO
    #org.springframework.kafka: DEBUG
    #org.apache.kafka: DEBUG

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - ssl-bitnami-kafka.azure.buildit.sh:9093
      bindings:
        input:
          binder: kafka
          destination: test
          content-type: application/json
          group: input-group-1
        output:
          binder: kafka
          destination: test
          group: output-group-1
          content-type: application/json

  kafka:
    properties:
      ssl.endpoint.identification.algorithm:
      security.protocol: SSL

    ssl:
      protocol: SSL

#      trust-store-location: file://${vcap.services.mccaskill.credentials.truststore1-path}
#      trust-store-password: ${vcap.services.mccaskill.credentials.truststore1-password}
#      trust-store-type: ${vcap.services.mccaskill.credentials.truststore1-type}
#
#      key-store-location: file://${vcap.services.mccaskill.credentials.keystore1-path}
#      key-store-password: ${vcap.services.mccaskill.credentials.keystore1-password}
#      key-store-type: ${vcap.services.mccaskill.credentials.keystore1-type}
