server:
  port: 8081
spring:
  security:
    user:
      name: testadmin
      password: password
      manager:
  kafka:
    consumer:
      bootstrap-servers: ssl-bitnami-kafka.azure.buildit.sh:9093
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      ssl.trust-store-location: base64:MIIG3gIBAzCCBpcGCSqGSIb3DQEHAaCCBogEggaEMIIGgDCCBnwGCSqGSIb3DQEHBqCCBm0wggZpAgEAMIIGYgYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUS1Z3SGU/Wn7G5W+zI+XFeFqmcRkCAwDDUICCBii5DplfwmUZa7COHJWz2jKxmnOtXUHl9EdJ/1pxZzAb70Iq3zNW4+MojkMPkvBpYv1BSWAk40ZjtnTRDNuAZeAXobL1baIcBb9wj8gT3EE9XD09w07G/Vv9nnAkufiduQV1pCIKBnXafzj6yEykh988sLLBpmAdGO3tJ5iJT9HGh5j+PlHlfmwcUGTonlxLNe2pFd+CY+zwfXudi4E2PfCkQSRCYjCTKB2ZWuGt19t53pY4Nj0j0MKpplOXhGLNqRZknYH837lCWXOtnSC4RZRe50kzUVed+1X/pBTaRqgtAiyQs8dYjM9tXblOX3huTzEUlKOSHJofji4PJlofyHssPZtWdZ13ji/iLwosKpNQ+/rO4hs3ANSQhoUCS24Yd/YNgcoSUcY5SqQ3yuWGwRILaTtgs5HfCvBYIO6h5RZprkR15y6G6dUefNITm56YYp5AUmJSV6z+4atOzZvCnc7MQ7TUi7skPy71o0wWGs2DUisvhRcBPYWg8HapQlC5ayZwxfEeSkZ+nYfxSlAU1EG3ZxGrRyxlkUNh1Kz2Dz3dzHIz/9xYIB5wa3GJvClJQLNB3nn/bU0ddTBSgvW4AHuylaQg4DrHf+usGCP1KNod8QfJmgB7k+guVBRINOzTIIUPaaPe653masGinvMKBnieL5Vo4nVK2Uw1Hxl6MYoVG8VN7lLEUdChV1vukXUs0YutUYOfF/aChUKKzilGpKG/v7RSB+TTjYTMutwkYCho4c+JyWbHMkizLNJTw9LzuSvaey4XDAi2sI+B9IZXSX0hWvBi+ETW9V++0kLTRvs79qddoZ/gVSIOd8i1I9JcAA+ESW6tOoCDP9zYRDF9V4qicwzubEUqL/bCzul+02Nud9tRfib41+k8z4zj56SIe9mQB5ONb86+sLK4A5Dq1YgL1iZiLeUcKZxLCLY+fCNRAyFLLVsKAaa3xCZuEk33NebfpVvkRHPlfn/vV833BuVzTtr5qWVO9wtNXrhE+Wgw9aVyzxHmDi1n5vbS5AUKKa3DzjP+2vyQb2T9HFd1u6wJQ+q114/Mm7rkR7OElCMJvmqG/slqENu+/M3o30DhaBMiMrYi8GOCHWKGwZahl7OAJ+LzMQurQSnvX4+FFyesSksJXGj+30vw6eNqQu02Yl4Mc2SAkd7S4YOCfWIwOVSdh28HEAs8zbAFhLohLqg7HeoYXp+Sor9mJKlOxu2mnCLvyOrvMZ4rBdUrnmJ2ywWJMfssSXSdEHhh+w3K3CNDz+UzAUkqkW0qVTJTrHlm2sy1TL1wb2oSKJYi+4K+0yAcF8OnMUqUkgzxYNFtunv21LzoIjr9G2YOBFNYy2l+kfHfuoRyGEKHDBMJ6cZJ8Zd+DGh9v5OThliHSlur0z9W6VPWufIjFngMaZM/p1Ht3eOebK3bGrcdUrbMhvOl43ALy4KA7vKyAp8tZpy5oI2MPxFaBRI37r7XBs9yDNhAcF+cHryXOsbbgVPGoMt9ggvruTDZ790alPfZHrZBdTCeWZr8qt05kfJFjn+JL21MPxYVIbdShRc++KW1C6QR+9SlntuSywr7FOfDoGGoQPgXbNyvrAFy1hH+Oe246uD6BHjiROtJM1Tvpi1OHuesuz9dn6hzmfNSUgVNq0q/ZJcayZbgRK8cQKdr4je2wUdzGFy65f4DuZSHT8HMmCOvDmiL3S821q1BPXfoZ8I4NEnJdek+yZdLIXPrXeEcrWsUajFIaV2I2Mr+RDnhQetKCl+zrxies9tQErV7+R/wq5Ztp4z4UGHYNpmsij9uIGnpGFaZckbIVDTtOg28FZ0yp9m0CtU3omN6CsIGaA50Y5J5cCauxY3mXWklENMmiE5qX1agXgxwPjvaX0T/LNJxdyJDENOigR5JL8xVWPqJLWeVVP7IKk3BTgZfqexjgFJxbv2iJkZvfSxkvDM2rv5QPWeVoU1K75Aq0VPVRaG3t9ZBiHV6KPPIMk7FhXdG4rcYVmhZHV5VBWe/AIUuGK+glYq2TAULDrQg4T2beRL3IthKK0A9XM1Lcend1CcCwfeguJq0r8JtclYmTUhl1vvAVM6Tk50xQ4OMM36v919YjXKSCIGyEo9ZjNQqMD4wITAJBgUrDgMCGgUABBSp5wtCQdEWHHBx8+kbfrFeK5reIQQU1BFc3OddmMQ9QwhtKJgWe4nZgx4CAwGGoA==
      ssl.trust-store-password: KeepItSimple123
      ssl.key-store-location: /home/vcap/app/certs/ssldemo.keystore
      ssl.key-store-password: KeepItSimple123
      ssl.key-password: KeepItSimple123
      ssl.protocol: TLSv1.2
      ssl.trust-store-type: PKCS12
      ssl.key-store-type: PKCS12
    producer:
      bootstrap-servers: ssl-bitnami-kafka.azure.buildit.sh:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl.trust-store-location: /home/vcap/app/certs/client.truststore
      ssl.trust-store-password: KeepItSimple123
      ssl.key-store-location: /home/vcap/app/certs/ssldemo.keystore
      ssl.key-store-password: KeepItSimple123
      ssl.key-password: KeepItSimple123
      ssl.protocol: TLSv1.2
      ssl.trust-store-type: PKCS12
      ssl.key-store-type: PKCS12